Repository mozilla/fxa-profile-server, pull requests merged in 2018-04, with the labels that each got.

#315 fix(mozlog): deprecation
  lib/logging/index.js
Labels: train-110, waffle:active

#317 fix(npm): update to npm5
  npm-shrinkwrap.json
Labels: waffle:active

#318 feat(cache): Clear cache when receiving a "profileDataChanged" event.
  lib/events.js
  test/events.js
Labels: waffle:review

#319 feat(node): update to node 8
  .travis.yml
  Dockerfile-build
  package.json
Labels: waffle:active
