Repository mozilla/fxa-profile-server, pull requests merged in 2018-10, with the labels that each got.

#345 Release v1.122.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#346 Release v1.123.0
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#347 fix(deps): update to latest Sinon
  npm-shrinkwrap.json
  package.json
  test/mysql.js
Labels: auto-merge, waffle:active

#344 fix(deps): add filtered npm audit
  .nsprc
  .travis.yml
  npm-shrinkwrap.json
  package.json
Labels: train-124
